#todo 你的建表语句,包含索引
CREATE TABLE `qu_order` (
                            `id` bigint NOT NULL COMMENT 'ID',
                            `create_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '创建者',
                            `create_time` datetime(6) DEFAULT NULL COMMENT '创建时间',
                            `delete_flag` bit(1) DEFAULT NULL COMMENT '删除标志 true/false 删除/未删除',
                            `update_by` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '更新者',
                            `update_time` datetime(6) DEFAULT NULL COMMENT '更新时间',
                            `can_return` bit(1) DEFAULT NULL COMMENT '订单是否支持原路退回',
                            `cancel_reason` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '订单取消原因',
                            `client_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '订单来源',
                            `complete_time` datetime(6) DEFAULT NULL COMMENT '完成时间',
                            `consignee_address_id_path` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '地址id '',''分割',
                            `consignee_address_path` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '地址名称  '',''分割"',
                            `consignee_detail` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '详细地址',
                            `consignee_mobile` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '收件人手机',
                            `consignee_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '收件人姓名',
                            `deliver_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '货运状态',
                            `discount_price` double(10,2) DEFAULT NULL COMMENT '优惠的金额',
  `flow_price` double(10,2) DEFAULT NULL COMMENT '总价格',
  `freight_price` double(10,2) DEFAULT NULL COMMENT '运费',
  `goods_num` int DEFAULT NULL COMMENT '商品数量',
  `goods_price` double(10,2) DEFAULT NULL COMMENT '商品价格',
  `logistics_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '物流公司CODE',
  `logistics_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '物流公司名称',
  `logistics_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '发货单号',
  `logistics_time` datetime(6) DEFAULT NULL COMMENT '送货时间',
  `member_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '会员ID',
  `member_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '用户名',
  `need_receipt` bit(1) DEFAULT NULL COMMENT '是否需要发票',
  `order_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '订单状态',
  `order_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '订单类型',
  `parent_order_sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '是否为其他订单下的订单，如果是则为依赖订单的sn，否则为空',
  `pay_order_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付方式返回的交易号',
  `pay_status` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '付款状态',
  `payment_method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '支付方式',
  `payment_time` datetime(6) DEFAULT NULL COMMENT '支付时间',
  `price_detail` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '价格详情',
  `promotion_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '是否为某订单类型的订单，如果是则为订单类型的id，否则为空',
  `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '买家订单备注',
  `store_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '店铺ID',
  `store_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '店铺名称',
  `sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '订单编号',
  `trade_sn` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '交易编号 关联Trade',
  `weight` double(10,2) DEFAULT NULL COMMENT '订单商品总重量',
  `qr_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '提货码',
  `update_price` double(10,2) DEFAULT NULL COMMENT '修改价格',
  `distribution_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '分销员ID',
  `delivery_method` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '配送方式',
  `use_platform_member_coupon_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '使用的平台会员优惠券id',
  `use_store_member_coupon_ids` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '使用的店铺会员优惠券id(,区分)',
  `receivable_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '微信支付流水号',
  `order_promotion_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `verification_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '虚拟商品核验码',
  `tenant_id` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT '000000' COMMENT '租户ID',
  `use_points` bigint DEFAULT NULL COMMENT '使用积分数量',
  `points_price` double(10,2) DEFAULT NULL COMMENT '积分抵扣价格',
  `use_enterprise_points` double(10,2) DEFAULT NULL COMMENT '使用的企业额度',
  `enterprise_points_price` double(10,2) DEFAULT NULL COMMENT '企业额度抵扣价格',
  `oms_return_status` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '取消订单OMS返回结果',
  `contract_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '企业购合同编号',
  `settle_flag` int DEFAULT NULL COMMENT '结算订单标记',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `order_sn` (`sn`(191)) USING BTREE COMMENT '订单编号索引',
  KEY `member_id` (`member_id`(191)) USING BTREE COMMENT '会员id索引',
  KEY `store_id` (`store_id`(191)) USING BTREE COMMENT '店铺id索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC COMMENT='订单表';


